-- DEPRECATED: Project KEYSTONE now uses PostgreSQL + Flyway.
-- Do not edit or run this legacy MySQL schema for new environments.
-- The authoritative schema is:
-- backend/src/main/resources/db/migration/V1__baseline_schema.sql
--
-- Run with:
--   docker compose up --build
--
-- Flyway creates and versions the PostgreSQL schema automatically.
